// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Program Recommendation AI agent.
 *
 * - recommendPrograms - A function that handles the program recommendation process.
 * - RecommendProgramsInput - The input type for the recommendPrograms function.
 * - RecommendProgramsOutput - The return type for the recommendPrograms function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendProgramsInputSchema = z.object({
  background: z
    .string()
    .describe("Applicant's educational and professional background."),
  interests: z.string().describe("Applicant's areas of interest."),
  statementOfPurpose: z
    .string()
    .describe('Applicant statement of purpose for the program.'),
});

export type RecommendProgramsInput = z.infer<typeof RecommendProgramsInputSchema>;

const RecommendProgramsOutputSchema = z.object({
  programRecommendations: z
    .array(z.string())
    .describe('A list of recommended programs tailored to the applicant.'),
  reasoning: z
    .string()
    .describe('Explanation of why these programs were recommended.'),
});

export type RecommendProgramsOutput = z.infer<typeof RecommendProgramsOutputSchema>;

export async function recommendPrograms(
  input: RecommendProgramsInput
): Promise<RecommendProgramsOutput> {
  return recommendProgramsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendProgramsPrompt',
  input: {schema: RecommendProgramsInputSchema},
  output: {schema: RecommendProgramsOutputSchema},
  prompt: `You are an expert academic advisor. A prospective student has provided their background, interests, and statement of purpose. Based on this information, recommend programs that would be a good fit for them.

Applicant Background: {{{background}}}
Applicant Interests: {{{interests}}}
Statement of Purpose: {{{statementOfPurpose}}}

Consider a variety of programs, including those the applicant may not have initially considered. Provide a brief reasoning for each recommendation.
`,
});

const recommendProgramsFlow = ai.defineFlow(
  {
    name: 'recommendProgramsFlow',
    inputSchema: RecommendProgramsInputSchema,
    outputSchema: RecommendProgramsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
